Repository FEMessage/create-nuxt-app, pull requests merged in 2019-10, with the labels that each got.

#95 fix: mobile模板兼容全面屏
  template/frameworks/mobile/assets/global.less
  template/nuxt/nuxt.config.js
Labels: bug

#96 chore: 更新 `el-form-renderer`
  template/_package.json
  template/frameworks/multiple/yarn.lock
  template/frameworks/single/yarn.lock
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: chore

#97 chore: 更新 el-data-table、upload-to-ali 依赖
  template/_package.json
  template/frameworks/multiple/yarn.lock
  template/frameworks/single/yarn.lock
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: chore

#98 refactor: 梳理cli逻辑
  .eslintrc
  .eslintrc.js
  .prettierrc
  bin/cli.js
  generator/GeneratorContext.js
  generator/Template.js
  generator/config.js
  generator/saofile.js
  package.json
  template.config.js
  template/_package.json
  test/index.test.js
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
  yarn.lock
Labels: refactor

#103 feat: 保持模板的@femessage组件最新
  bin/cli.js
  generator/saofile.js
  package.json
  template/framework-mobile/_package.json
  template/framework-multiple/_package.json
  template/framework-single/_package.json
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: enhancement

#104 fix: 为了配合eslint使用rest/spread操作符，设置engine版本node: >=8.3.0
  package.json
Labels: bug
