Repository FEMessage/create-nuxt-app, pull requests merged in 2019-09, with the labels that each got.

#76 chore: 改善 linter
  template/_package.json
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: chore

#77 chore: lint template
  template/commitlint.config.js
  template/frameworks/element-ui/plugins/element.js
  template/frameworks/filters/plugins/filters.js
  template/frameworks/mobile/postcss.config.js
  template/frameworks/multiple/components/scrollbar/index.less
  template/nuxt/nuxt.config.js
Labels: chore

#78 fix: 更正忽略 `export.less` 文件
  template/frameworks/multiple/.stylelintignore
  template/frameworks/multiple/assets/export.less
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: bug

#80 chore: 使用 gren 生成 release notes
  .grenrc.js
  notify.sh
  package.json
  yarn.lock
Labels: chore

#79 feat: 添加 `@nuxtjs/pwa`
  README.md
  template.config.js
  template/_package.json
  template/frameworks/axios/plugins/axios.js
  template/frameworks/jest/test/getRouterBase.test.js
  template/frameworks/mobile/yarn.lock
  template/frameworks/multiple/yarn.lock
  template/frameworks/single/yarn.lock
  template/frameworks/utils/utils/index.js
  template/nuxt/nuxt.config.js
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: enhancement

#84 feat: LOGO 可以根据`项目名称`自适应变动
  template/frameworks/components/components/logo.vue
  template/frameworks/mobile/pages/my.vue
  template/frameworks/multiple/components/layout-head.vue
  template/frameworks/multiple/layouts/login.vue
  template/frameworks/single/layouts/default.vue
  template/frameworks/single/layouts/login.vue
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: enhancement

#10 ci: deploy to preview all apps
  .travis.yml
  bin/deploy/build.js
  bin/deploy/env.json
  bin/deploy/index.html
  generator/Template.js
  package.json
  yarn.lock
Labels: ci

#85 feat: active dev source map
  template/nuxt/nuxt.config.js
Labels: enhancement

#87 feat: 新增 upload-to-ali 模块，并添加webpack打包优化示例
  template/_package.json
  template/frameworks/mobile/yarn.lock
  template/frameworks/multiple/yarn.lock
  template/frameworks/single/yarn.lock
  template/nuxt/nuxt.config.js
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: enhancement
