Repository FEMessage/create-nuxt-app, pull requests merged in 2019-12, with the labels that each got.

#122 fix: wrong full-width comma in stylelintrc
  template/framework/.stylelintrc
Labels: bug

#123 chore: 正确注册 Toast；增加 eslint-plugin-jest；升级 nuxt
  template/framework-mobile/_package.json
  template/framework-mobile/plugins/vant.js
  template/framework-mobile/yarn.lock
  template/framework-multiple/_package.json
  template/framework-multiple/yarn.lock
  template/framework-single/_package.json
  template/framework-single/yarn.lock
  template/framework/_.eslintrc.js
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: chore

#124 fix: 修复自适应计算出错的 bug
  template/framework-mobile/postcss.config.js
Labels: bug

#125 fix: 桌面级全局引入 `element-ui` 样式, 避免导致样式覆盖而丢失
  template/framework-multiple/_package.json
  template/framework-multiple/yarn.lock
  template/framework-single/_package.json
  template/framework-single/yarn.lock
  template/framework/nuxt.config.js
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: bug

#127 fix: 桌面模板现已可以登录跳转到首页
  bin/deploy/build.js
  template/framework/nuxt.config.js
Labels: bug

#126 perf: 移除 ali-oss 的引入
  template/framework/nuxt.config.js
Labels: performance

#129 feat: 模板增加 google-analytics
  template/framework-mobile/_package.json
  template/framework-mobile/yarn.lock
  template/framework-multiple/_package.json
  template/framework-multiple/yarn.lock
  template/framework-single/_package.json
  template/framework-single/yarn.lock
  template/framework/nuxt.config.js
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: enhancement

#130 chore: 修改favicon
  template/modules/meta/const/meta.js
Labels: chore

#131 chore: add lhci
  .travis.yml
Labels: chore

#128 perf: 模板里的img标签替换成v-img组件
  template/framework-mobile/_package.json
  template/framework-mobile/pages/goods-detail.vue
  template/framework-mobile/pages/index.vue
  template/framework-mobile/pages/my.vue
  template/framework-mobile/pages/order-list.vue
  template/framework-mobile/plugins/vant.js
  template/framework-multiple/_package.json
  template/framework-multiple/components/layout-head.vue
  template/framework-multiple/layouts/login.vue
  template/framework-multiple/pages/index.vue
  template/framework-single/_package.json
  template/framework-single/layouts/default.vue
  template/framework-single/layouts/login.vue
  template/framework-single/pages/index.vue
  template/modules/components-desktop/components/menu-item.vue
  template/modules/element-ui/plugins/element.js
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: performance

#132 chore: only run lhci on dev branch
  .travis.yml
  lhci.sh
  notify.sh
  package.json
Labels: chore

#136 chore(deps): upgrade gren
  .grenrc.js
  package.json
  yarn.lock
Labels: dependencies

#138 refactor: package.json 使用合成策略 & 修复 yarn lint 在 windows 下报错的问题
  generator/saofile.js
  generator/utils.js
  template/framework-base/.editorconfig
  template/framework-base/.npmignore
  template/framework-base/.prettierrc
  template/framework-base/.stylelintrc
  template/framework-base/README.md
  template/framework-base/_.eslintrc.js
  template/framework-base/_.gitignore
  template/framework-base/_package.json
  template/framework-base/assets/README.md
  template/framework-base/commitlint.config.js
  template/framework-base/components/README.md
  template/framework-base/layouts/README.md
  template/framework-base/middleware/README.md
  template/framework-base/nuxt.config.js
  template/framework-base/pages/README.md
  template/framework-base/plugins/README.md
  template/framework-base/static/README.md
  template/framework-base/static/favicon.ico
  template/framework-base/static/icon.png
  template/framework-base/store/README.md
  template/framework-mobile/_package.json
  template/framework-mobile/yarn.lock
  template/framework-multiple/_package.json
  template/framework-multiple/yarn.lock
  template/framework-single/_package.json
  template/framework-single/yarn.lock
  test/snapshots/index.test.js.md
  test/snapshots/index.test.js.snap
Labels: refactor
